@port = 5000
@resource=products
@baseURL = http://localhost:{{port}}/api/v1/{{resource}}
// Use a productID that was returned when you retrieved all products: 
@productID = 63bab39b42be2c3bc3aa8d1e

### Create product
POST {{baseURL}} HTTP/1.1
Content-Type: application/json

{
    "brand": "adidas Originals",
    "model": "Retropy E5",
    "category": "sneakers",
    "priceNormal": "1105",
    "priceCurrent": "718",
    "currency": "DKK",
    "gender": "unisex",
    "image": "adidas-retropy-e5.webp",
    "sizes": [
        { "size": 39, "available": true, "availableInDays": 0 },
        { "size": 40, "available": true, "availableInDays": 0 },
        { "size": 41, "available": true, "availableInDays": 0 },
        { "size": 42, "available": true, "availableInDays": 0 },
        { "size": 43, "available": false, "availableInDays": 14 },
        { "size": 44, "available": false, "availableInDays": 14 },
        { "size": 45, "available": false, "availableInDays": 7 }
    ]
}


### Get all products
GET {{baseURL}} HTTP/1.1
Content-Type: application/json

### Delete all products
DELETE {{baseURL}} HTTP/1.1
Content-Type: application/json

### Get product
GET {{baseURL}}/{{productID}} HTTP/1.1
Content-Type: application/json

### Update product
PATCH {{baseURL}}/{{productID}} HTTP/1.1
Content-Type: application/json

{
    "brand": "Adidas Originals",
    "image": "adidas-retropy-e5.webp"
}

### Delete product
DELETE {{baseURL}}/{{productID}} HTTP/1.1
Content-Type: application/json