@port = 5000
@resource=products
@baseURL = http://localhost:{{port}}/api/v1/{{resource}}
// Use a productID that was returned when you retrieved all products: 
@productID = 63b7eed4727ff1ae972cb2a8


### Create product
POST {{baseURL}} HTTP/1.1
Content-Type: application/json

{
    "brand": "ASOS",
    "model": "ew4t-41222",
    "category": "trail runners",
    "priceNormal": "449",
    "priceCurrent": "579",
    "gender": "men"
}

### Get all products
GET {{baseURL}} HTTP/1.1
Content-Type: application/json

### Delete all products
DELETE {{baseURL}} HTTP/1.1
Content-Type: application/json

### Get product
GET {{baseURL}}/{{productID}} HTTP/1.1
Content-Type: application/json

### Update product
PATCH {{baseURL}}/{{productID}} HTTP/1.1
Content-Type: application/json

{
    "gender": "women"
}

### Delete product
DELETE {{baseURL}}/{{productID}} HTTP/1.1
Content-Type: application/json